
name: CI

on: [push]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: npm install jest
      run: |
        npm install --save-dev jest
    - name: npm run test
      run: |
        npm run test

